export const sliderInfo = [
  {
    icon: 'first-aid',
    title: 'Healthcare',
    body: 'DDI has worked alongside healthcare providers for over 25 years, easing financial concerns and constraints through our flexible leasing and financing solutions. We are experts at helping you effectively manage cash flow so you can continue to focus on providing quality care.',
  },
  {
    icon: 'graduation-cap',
    title: 'Education',
    body: 'Technology is the future of innovation in the modern classroom. DDI works with hundreds of school districts, public and private, providing the tools to reinvent education and helping bring their visions of learning in the 21st century to life.',
  },
  {
    icon: 'camera',
    title: 'Media',
    body: 'From broadcasting to production and distribution, media companies rely on DDI to stay current and competitive in the ever-evolving entertainment industry, without pressing the “pause button” on growth.',
  },
  {
    icon: 'shopping-cart',
    title: 'Retail',
    body: 'From disruptive growth companies to Fortune 500s, DDI offers tailored and appropriate financing solutions to help your sales boom, keep your data safe and ensure your offerings remain competitive.',
  },
  {
    icon: 'cogs',
    title: 'Manufacturing',
    body: 'The need for state-of-the-art technology to enhance manufacturing and workflow operations is critical. Our leasing solutions help maximize your company’s productivity and efficiency.',
  },
  {
    icon: 'money-bill-wave',
    title: 'Financial',
    body: 'In no other industry is the “Internal Rate of Return” dynamic more evident. DDI’s flexible and creative solutions allow financial institutions to keep their capital for operations, rather than solving technology problems, all while fitting cleanly into allocated budgets.',
  },
  {
    icon: 'laptop',
    title: 'Managed Service Providers',
    body: 'In the most rapidly evolving landscape, establish, expand and reinvent your business with the latest technologies to ensure your customers will not look elsewhere. DDI offers the solutions to keep your technology current and help your business to thrive.',
  },
  {
    icon: 'bed',
    title: 'Hospitality',
    body: 'Leading hospitality brands depend on DDI to help them connect with guests and improve operational efficiencies so they can deliver the best possible experiences to their customers.',
  },
];

export const teamInfo = {
  'Ellen-Arlauskas': {
    image: null,
    name: 'Ellen Arlauskas',
    title: 'Director of Leasing Administration',
    location: 'Bedminster, NJ',
    body: 'Ellen joined DDI Capital, Inc. in 1997 after working for Capital Guardian Trust Company, part of the Capital Group Companies, an investment services organization for corporate pension and retirement plans and Andersen Consulting, an IT consulting and services firm.  Ellen comes with over 30 years experience in the finance, investment services, and consulting industries.  As Director of Leasing Administration, her primary responsibilities include the management of all in-house leasing administration support as well as client relations and vendor support.  Ellen is a graduate of Berkeley College.',
    email: 'ellena@ddicapitalinc.com',
  },
  'Steve-Case': {
    image: null,
    name: 'Steve Case',
    title: 'Managing Director',
    location: 'Charlotte, NC',
    body: 'Steve has been successfully working in the equipment finance industry for over 30 years with various customers, vendors and manufacturers. Growing up in New York he graduated with an Electrical Technology degree then moved to the Carolina’s where he has lived since. During his career, he has worked both the marketing side and the financial side of the financial/sales product industry.',
    email: 'stevec@ddicapitalinc.com',
  },
  'Mike-Dolan': {
    image: null,
    name: 'Mike Dolan',
    title: 'Managing Director',
    location: 'Spring Lake, NJ',
    body: 'Mike began his career at DDI in January 2015. He has over 22 years of experience in finance. Prior to joining DDI, Mike spent 13 years running equity research sales operations at Instinet and Axiom Capital. His focus was in the Oil and Gas and Biotechnology industries, providing alternative and customized research to multi-billion dollar Hedge Funds and Investment Advisors. Prior to that, Mike was a Sales Trader at Sanford Bernstein and an Institutional Wholesaler for Goldman Sachs Asset Management.  Mike graduated from St. Joseph’s University in Philadelphia in 1993 and lives in Fair Haven, NJ.',
    email: 'mdolan@ddicapitalinc.com',
  },
  'Christopher-Flammer': {
    image: null,
    name: 'Christopher Flammer',
    title: 'Manging Director',
    location: 'Spring Lake, NJ',
    body: 'Chris has worked at DDI Capital since 1998.  He started the “vendor” relationship program as a sales representative and is now Managing Director of the Spring Lake office.  Chris is a graduate of Saint Joseph’s University, resides in Fair Haven, NJ and enjoys spending time playing golf with his clients.',
    email: 'chrisf@ddicapitalinc.com',
  },
  'Kevin-Moran': {
    image: null,
    name: 'Kevin Moran',
    title: 'Manager, Wholesale & Retail Sales',
    location: 'Bedminster, NJ',
    body: 'Kevin joined DDI Capital in 2013 after working 30+ years in the steamship industry.  As the Senior Manager of Wholesale / Retail Sales, Kevin is responsible for the reselling of computer equipment to consignment centers throughout the country.  Kevin is a graduate of Lycoming College with a BS in Business Administration.',
    email: 'kevinm@ddicapitalinc.com',
  },
  'Mike-Moran': {
    image: null,
    name: 'Mike Moran',
    title: 'Chief Executive Officer',
    location: 'Bedminster, NJ',
    body: 'Mike Co-Founded DDI Capital, Inc. in 1995 after spending 8 years working at XL/ Datacomp, Inc., a Premier IBM Business partner. Prior to his years at XLDC, Mike worked at IBM as a salesman in various NJ sales locations.  Mike received a BA from Lycoming College with a degree in Economics and lives in Bedminster, NJ.',
    email: 'mikem@ddicapitalinc.com',
  },
  'Terry-Moran': {
    image: null,
    name: 'Terry Moran',
    title: 'Vice President',
    location: 'Bedminster, NJ',
    body: 'Terry began working at DDI Capital in 1995 and was the company’s first employee!  As Vice President, Terry focuses on both corporate and education clients.  Prior to working at DDI, Terry worked for six years at an IBM reseller.  DDI continues to support IBM clients, particularly in the iSeries market.  Terry is also a partner in the DDI Company, Stonehenge Resources – a staffing and recruiting firm.  Terry is a graduate of Fairfield University.',
    email: 'terrym@ddicapitalinc.com',
  },
  'Christian-Mosiciki': {
    image: null,
    name: 'Christian Mosiciki',
    title: 'Managing Director',
    location: 'Quogue, NJ',
    body: 'Christian joined DDI Capital in mid-2015 after 8 successful years as an institutional equity salesperson at several broker-dealers and banks (most recently FBR, Inc.). Christian graduated from Middlebury College with a degree in English in 2006 and has lived in New York City ever since. He initially spent 3 years in public/investor relations before pursuing a career in financial product/services sales.',
    email: 'cmoscicki@ddicapitalinc.com',
  },
  'Greg-Nappi': {
    image: null,
    name: 'Greg Nappi',
    title: 'Chief Financial Officer',
    location: 'Bedminster, NJ',
    body: 'Greg Joined DDI Capital, Inc. in 1999 after working in public accounting for 12 years. Greg sits on the board of NEFA (National Equipment Finance Association). Greg received a BS in Accounting from St. Thomas Aquinas College and lives in Waldwick, NJ.',
    email: 'gregn@ddicapitalinc.com',
  },
  'Tom-Tensfeldt': {
    image: null,
    name: 'Tom Tensfeldt',
    title: 'Managing Director',
    location: 'Jacksonville, FL',
    body: 'Tom began working at DDI Capital in 2001.  Prior to that, he worked in the leasing industry with ACS Capital Corporation focusing on retail customer relationships.  From that experience, Tom prides himself on being the liaison between his customers and vendors.  Tom lives in Ponte Vedra Beach, Florida.',
    email: 'tomt@ddicapitalinc.com',
  },
  'Brett-Ugles': {
    image: null,
    name: 'Brett Ugles',
    title: 'Vice President, Captial Markets',
    location: 'Jacksonville, FL',
    body: 'Brett has been in the leasing industry since 1986, holding various operations and sales positions with Bell Atlantic Tricon Leasing. After moving to Copelco Capital, Brett joined DDI in 2000 and is responsible for banking relationships and customer credit.',
    email: 'brettu@ddicapitalinc.com',
  },
};
